// <auto-generated />
using System;
using EFCore5TPTBug;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EFCore5TPTBug.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20201123150221_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EFCore5TPTBug.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("referral_pkey");

                    b.ToTable("referral");
                });

            modelBuilder.Entity("EFCore5TPTBug.UserReferral", b =>
                {
                    b.HasBaseType("EFCore5TPTBug.Referral");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.ToTable("user_referral");
                });

            modelBuilder.Entity("EFCore5TPTBug.UserReferral", b =>
                {
                    b.HasOne("EFCore5TPTBug.Referral", null)
                        .WithOne()
                        .HasForeignKey("EFCore5TPTBug.UserReferral", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
